/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPointsRouteImport } from './routes/api/points'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as IncidentIdIndexRouteImport } from './routes/incident.$id.index'
import { Route as IncidentIdShareRouteImport } from './routes/incident.$id.share'
import { Route as IncidentIdUpdateRouteImport } from './routes/incident.$id.update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPointsRoute = ApiPointsRouteImport.update({
  id: '/api/points',
  path: '/api/points',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentIdIndexRoute = IncidentIdIndexRouteImport.update({
  id: '/incident/$id/',
  path: '/incident/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentIdShareRoute = IncidentIdShareRouteImport.update({
  id: '/incident/$id/share',
  path: '/incident/$id/share',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentIdUpdateRoute = IncidentIdUpdateRouteImport.update({
  id: '/incident/$id/update',
  path: '/incident/$id/update',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/points': typeof ApiPointsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/incident/$id/share': typeof IncidentIdShareRoute
  '/incident/$id/update': typeof IncidentIdUpdateRoute
  '/incident/$id/': typeof IncidentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/points': typeof ApiPointsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/incident/$id/share': typeof IncidentIdShareRoute
  '/incident/$id/update': typeof IncidentIdUpdateRoute
  '/incident/$id': typeof IncidentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/points': typeof ApiPointsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/incident/$id/share': typeof IncidentIdShareRoute
  '/incident/$id/update': typeof IncidentIdUpdateRoute
  '/incident/$id/': typeof IncidentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/points'
    | '/api/transcribe'
    | '/incident/$id/share'
    | '/incident/$id/update'
    | '/incident/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/points'
    | '/api/transcribe'
    | '/incident/$id/share'
    | '/incident/$id/update'
    | '/incident/$id'
  id:
    | '__root__'
    | '/'
    | '/api/points'
    | '/api/transcribe'
    | '/incident/$id/share'
    | '/incident/$id/update'
    | '/incident/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPointsRoute: typeof ApiPointsRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  IncidentIdShareRoute: typeof IncidentIdShareRoute
  IncidentIdUpdateRoute: typeof IncidentIdUpdateRoute
  IncidentIdIndexRoute: typeof IncidentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/points': {
      id: '/api/points'
      path: '/api/points'
      fullPath: '/api/points'
      preLoaderRoute: typeof ApiPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident/$id/': {
      id: '/incident/$id/'
      path: '/incident/$id'
      fullPath: '/incident/$id/'
      preLoaderRoute: typeof IncidentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident/$id/share': {
      id: '/incident/$id/share'
      path: '/incident/$id/share'
      fullPath: '/incident/$id/share'
      preLoaderRoute: typeof IncidentIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident/$id/update': {
      id: '/incident/$id/update'
      path: '/incident/$id/update'
      fullPath: '/incident/$id/update'
      preLoaderRoute: typeof IncidentIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPointsRoute: ApiPointsRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  IncidentIdShareRoute: IncidentIdShareRoute,
  IncidentIdUpdateRoute: IncidentIdUpdateRoute,
  IncidentIdIndexRoute: IncidentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
